# Site settings
title: Some random ramblings from a developer
header-img: img/home-bg.png
email: kirangp@gmail.com
copyright_name: kirangp
description: > # this means to ignore newlines until "baseurl:"
  I am interested in the art of development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kirangp
learn_profile: kirangp
email_username: kirangp@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
